#!/bin/sh
# Code generated by binstaller. DO NOT EDIT.
#
set -e
usage() {
  this=$1
  cat <<EOF
$this: download ${NAME} from ${REPO}

Usage: $this [-b bindir] [-d]
  -b sets bindir or installation directory, Defaults to ./bin
  -d turns on debug logging
   This installer is configured for v1.0.0 only.

 Generated by binstaller
  https://github.com/binary-install/binstaller
EOF
  exit 2
}

cat /dev/null <<EOF
------------------------------------------------------------------------
https://github.com/client9/shlib - portable posix shell functions
Public domain - http://unlicense.org
https://github.com/client9/shlib/blob/master/LICENSE.md
but credit (and pull requests) appreciated.
------------------------------------------------------------------------
EOF
is_command() {
  command -v "$1" >/dev/null
}
echoerr() {
  echo "$@" 1>&2
}
_logp=6
log_set_priority() {
  _logp="$1"
}
log_priority() {
  if test -z "$1"; then
    echo "$_logp"
    return
  fi
  [ "$1" -le "$_logp" ]
}
log_tag() {
  case $1 in
    0) echo "emerg" ;;
    1) echo "alert" ;;
    2) echo "crit" ;;
    3) echo "err" ;;
    4) echo "warning" ;;
    5) echo "notice" ;;
    6) echo "info" ;;
    7) echo "debug" ;;
    *) echo "$1" ;;
  esac
}
log_debug() {
  log_priority 7 || return 0
  echoerr "$(log_prefix)" "$(log_tag 7)" "$@"
}
log_info() {
  log_priority 6 || return 0
  echoerr "$(log_prefix)" "$(log_tag 6)" "$@"
}
log_err() {
  log_priority 3 || return 0
  echoerr "$(log_prefix)" "$(log_tag 3)" "$@"
}
log_crit() {
  log_priority 2 || return 0
  echoerr "$(log_prefix)" "$(log_tag 2)" "$@"
}
uname_os() {
  os=$(uname -s | tr '[:upper:]' '[:lower:]')
  case "$os" in
    msys*) os="windows" ;;
    mingw*) os="windows" ;;
    cygwin*) os="windows" ;;
  esac
  if [ "$os" = "sunos" ]; then
    if [ "$(uname -o)" = "illumos" ]; then
      os="illumos"
    else
      os="solaris"
    fi
  fi
  echo "$os"
}
uname_arch() {
  arch=$(uname -m)
  case $arch in
    x86_64) arch="amd64" ;;
    i86pc) arch="amd64" ;;
    x86) arch="386" ;;
    i686) arch="386" ;;
    i386) arch="386" ;;
    aarch64) arch="arm64" ;;
    armv5*) arch="armv5" ;;
    armv6*) arch="armv6" ;;
    armv7*) arch="armv7" ;;
  esac
  echo "${arch}"
}
uname_os_check() {
  os=$(uname_os)
  case "$os" in
    darwin) return 0 ;;
    dragonfly) return 0 ;;
    freebsd) return 0 ;;
    linux) return 0 ;;
    android) return 0 ;;
    midnightbsd) return 0 ;;
    nacl) return 0 ;;
    netbsd) return 0 ;;
    openbsd) return 0 ;;
    plan9) return 0 ;;
    solaris) return 0 ;;
    illumos) return 0 ;;
    windows) return 0 ;;
  esac
  log_crit "uname_os_check '$(uname -s)' got converted to '$os' which is not a GOOS value. Please file bug at https://github.com/client9/shlib"
  return 1
}
uname_arch_check() {
  arch=$(uname_arch)
  case "$arch" in
    386) return 0 ;;
    amd64) return 0 ;;
    arm64) return 0 ;;
    armv5) return 0 ;;
    armv6) return 0 ;;
    armv7) return 0 ;;
    ppc64) return 0 ;;
    ppc64le) return 0 ;;
    mips) return 0 ;;
    mipsle) return 0 ;;
    mips64) return 0 ;;
    mips64le) return 0 ;;
    s390x) return 0 ;;
    amd64p32) return 0 ;;
  esac
  log_crit "uname_arch_check '$(uname -m)' got converted to '$arch' which is not a GOARCH value.  Please file bug report at https://github.com/client9/shlib"
  return 1
}
http_download_curl() {
  local_file=$1
  source_url=$2
  header=$3
  if [ -z "$header" ]; then
    curl -fsSL -o "$local_file" "$source_url"
  else
    curl -fsSL -H "$header" -o "$local_file" "$source_url"
  fi
}
http_download_wget() {
  local_file=$1
  source_url=$2
  header=$3
  if [ -z "$header" ]; then
    wget -q -O "$local_file" "$source_url"
  else
    wget -q --header "$header" -O "$local_file" "$source_url"
  fi
}
http_download() {
  log_debug "http_download $2"
  if is_command curl; then
    http_download_curl "$@"
    return
  elif is_command wget; then
    http_download_wget "$@"
    return
  fi
  log_crit "http_download unable to find wget or curl"
  return 1
}
http_copy() {
  tmp=$(mktemp)
  http_download "${tmp}" "$1" "$2" || return 1
  body=$(cat "$tmp")
  rm -f "${tmp}"
  echo "$body"
}
github_release() {
  owner_repo=$1
  version=$2
  test -z "$version" && version="latest"
  giturl="https://github.com/${owner_repo}/releases/${version}"
  json=$(http_copy "$giturl" "Accept:application/json")
  test -z "$json" && return 1
  version=$(echo "$json" | tr -s '\n' ' ' | sed 's/.*"tag_name":"//' | sed 's/".*//')
  test -z "$version" && return 1
  echo "$version"
}
cat /dev/null <<EOF
------------------------------------------------------------------------
End of functions from https://github.com/client9/shlib
------------------------------------------------------------------------
EOF


hash_sha256() {
  TARGET=${1:-/dev/stdin}
  if is_command gsha256sum; then
    hash=$(gsha256sum "$TARGET") || return 1
    echo "$hash" | cut -d ' ' -f 1
  elif is_command sha256sum; then
    hash=$(sha256sum "$TARGET") || return 1
    echo "$hash" | cut -d ' ' -f 1
  elif is_command shasum; then
    hash=$(shasum -a 256 "$TARGET" 2>/dev/null) || return 1
    echo "$hash" | cut -d ' ' -f 1
  elif is_command openssl; then
    hash=$(openssl dgst -sha256 "$TARGET") || return 1
    echo "$hash" | cut -d ' ' -f 2
  else
    log_crit "hash_sha256 unable to find command to compute sha-256 hash"
    return 1
  fi
}

hash_compute() {
  hash_sha256 "$1"
}


untar() {
  tarball=$1
  strip_components=${2:-0} # default 0
  case "${tarball}" in
  *.tar.gz | *.tgz) tar --no-same-owner -xzf "${tarball}" --strip-components "${strip_components}" ;;
  *.tar.xz) tar --no-same-owner -xJf "${tarball}" --strip-components "${strip_components}" ;;
  *.tar.bz2) tar --no-same-owner -xjf "${tarball}" --strip-components "${strip_components}" ;;
  *.tar) tar --no-same-owner -xf "${tarball}" --strip-components "${strip_components}" ;;
  *.gz) gunzip "${tarball}" ;;
  *.zip)
    # unzip doesn't have a standard --strip-components
    # Workaround: extract to a subdir and move contents up if stripping
    if [ "$strip_components" -gt 0 ]; then
      extract_dir=$(basename "${tarball%.zip}")_extracted
      unzip -q "${tarball}" -d "${extract_dir}"
      # Move contents of the *first* directory found inside extract_dir up
      # This assumes wrap_in_directory=true convention
      first_subdir=$(find "${extract_dir}" -mindepth 1 -maxdepth 1 -type d -print -quit)
      if [ -n "$first_subdir" ]; then
        # Move all contents (* includes hidden files)
        mv "${first_subdir}"/* .
        # Optionally remove the now-empty subdir and the extract_dir
        rmdir "${first_subdir}"
        rmdir "${extract_dir}"
      else
        log_warn "Could not find subdirectory in zip to strip components from ${extract_dir}"
        # Files are extracted in current dir anyway, proceed
      fi
    else
      unzip -q "${tarball}"
    fi
    ;;
  *)
    log_err "untar unknown archive format for ${tarball}"
    return 1
    ;;
  esac
}

extract_hash() {
  TARGET=$1
  checksums=$2
  if [ -z "$checksums" ]; then
    log_err "extract_hash checksum file not specified in arg2"
    return 1
  fi
  BASENAME=${TARGET##*/}
  grep -E "([[:space:]]|/|\*)${BASENAME}$" "${checksums}" 2>/dev/null | tr '\t' ' ' | cut -d ' ' -f 1
}


hash_verify() {
  TARGET_PATH=$1
  SUMFILE=$2
  if [ -z "${SUMFILE}" ]; then
    log_err "hash_verify checksum file not specified in arg2"
    return 1
  fi
  got=$(hash_compute "$TARGET_PATH")
  if [ -z "${got}" ]; then
    log_err "failed to calculate hash: ${TARGET_PATH}"
    return 1
  fi
  # 1) “hash-only” line?
  if grep -i -E "^${got}[[:space:]]*$" "$SUMFILE" >/dev/null 2>&1; then
    return 0
  fi
  # 2) Check hash & file name match
  want=$(extract_hash "${TARGET_PATH}" "${SUMFILE}")
  if [ "$want" != "$got" ]; then
    log_err "hash_verify checksum for '$TARGET_PATH' did not verify ${want} vs ${got}"
    return 1
  fi
}


# --- Embedded Checksums (Format: VERSION:FILENAME:HASH) ---
EMBEDDED_CHECKSUMS="
1.0.0:sigspy-1.0.0.tar.gz:74559d3d3732b48f5877a1920ba25b05e7edeede1201077b28b281af9c8709a1
1.0.0:sigspy-1.0.0.tar.gz.sbom.json:255aaf2a067e56a1f41e82328d4227ae07aa0c230a91e0f148d6f15fb8e0a29a
1.0.0:sigspy_Darwin_arm64.tar.gz:01900d9087e1463b2823a49e8f363a6dcc4932889edbd6071899f1b2c39fa334
1.0.0:sigspy_Darwin_arm64.tar.gz.sbom.json:88963435fe32a96ad3ed54fa8721d34100e1eb2b48bba4566bd5bc37624ed929
1.0.0:sigspy_Darwin_x86_64.tar.gz:0d5aa3d6ddad2dec1490fdadbcdc54d6effb38273ef64fd8da5e22f564343687
1.0.0:sigspy_Darwin_x86_64.tar.gz.sbom.json:850b734d43abadd1eb0b0fb8afc37407163b0a7dade1c5691c737768da9c8858
1.0.0:sigspy_Linux_arm64.tar.gz:a39a88f9332b3da105a2b5362f6f8e63bbbc6b95223be7be290f0ab57182b911
1.0.0:sigspy_Linux_arm64.tar.gz.sbom.json:4159c4c4a3821bc90ea7736be7436ccc0b494d46d565593bfd59154c5e1e586e
1.0.0:sigspy_Linux_i386.tar.gz:8109dc683d2cc05d3c27c9522f0f18b8951b2746f37922ecdaf910dbfd75dfda
1.0.0:sigspy_Linux_i386.tar.gz.sbom.json:feddac49d511cd7335f4f459b04358f939808f6235dd9e477e13ad4d14afb6dc
1.0.0:sigspy_Linux_x86_64.tar.gz:e2b7a878c2a41f4015ac564576f98255c1744e206418d94b8647e50955a4fb10
1.0.0:sigspy_Linux_x86_64.tar.gz.sbom.json:bc9717f23ae0a79d39a6fc1eb8cc3b401870e44799daac887831df7145a79f61
1.0.0:sigspy_Windows_arm64.zip:1c1cf0966b41d050dd9e2ff0aa0a096d51cefd0af7488da3ea816d5672eedc3d
1.0.0:sigspy_Windows_arm64.zip.sbom.json:9969aeff94aafd43d3b591d17181c1dac46885e042675e66d4468f83e50ddf67
1.0.0:sigspy_Windows_i386.zip:3c75e825ee07ceb628031f4e0cce3f36bd20105e3797f828e2de10fd122b196c
1.0.0:sigspy_Windows_i386.zip.sbom.json:bf49ffbcce7143ef3a01ee00f94ffe3dd646925ab5738906b18d218e0dfdd070
1.0.0:sigspy_Windows_x86_64.zip:e45421cc5f74990e9dd2b7d21ffeee2ac005262f055ff30ade94d4e189f7fb07
1.0.0:sigspy_Windows_x86_64.zip.sbom.json:389acf4d22e8d9b6d9c8eaa8a49a67cae7b82cc995d8879ad0a8653472a16c3a"

# Find embedded checksum for a given version and filename
find_embedded_checksum() {
  version="$1"
  filename="$2"
  echo "$EMBEDDED_CHECKSUMS" | grep -E "^${version}:${filename}:" | cut -d':' -f3
}

parse_args() {
  BINDIR="${BINSTALLER_BIN:-${HOME}/.local/bin}"
  while getopts "b:dqh?x" arg; do
    case "$arg" in
    b) BINDIR="$OPTARG" ;;
    d) log_set_priority 10 ;;
    q) log_set_priority 3 ;;
    h | \?) usage "$0" ;;
    x) set -x ;;
    esac
  done
  shift $((OPTIND - 1))
  TAG="v1.0.0"
}

tag_to_version() {
  # Target version is set at generation time
  REALTAG="v1.0.0"
  VERSION=${REALTAG#v} # Strip leading 'v'
  TAG="$REALTAG"
  log_info "Installing ${NAME} version ${VERSION}"
}

capitalize() {
  input="$1"
  first_char=$(printf "%s" "$input" | cut -c1)
  first_upper=$(printf "%s" "$first_char" | tr '[:lower:]' '[:upper:]')
  printf "%s%s\n" "$first_upper" "$(printf "%s" "$input" | cut -c2-)"
}


resolve_asset_filename() {
  OS="$(capitalize "${OS}")"
  # --- Apply Rules ---
  ASSET_FILENAME=""
  if [ "${UNAME_ARCH}" = 'amd64' ] && true
  then
    ARCH='x86_64'
  fi
  if [ "${UNAME_ARCH}" = '386' ] && true
  then
    ARCH='i386'
  fi
  if [ "${UNAME_OS}" = 'windows' ] && true
  then
    EXT='.zip'
  fi
  if [ -z "${ASSET_FILENAME}" ]; then
    ASSET_FILENAME="${NAME}_${OS}_${ARCH}${EXT}"
  fi
}

execute() {
  STRIP_COMPONENTS=0
  CHECKSUM_FILENAME="checksums.txt"

  # --- Construct URLs ---
  GITHUB_DOWNLOAD="https://github.com/${REPO}/releases/download"
  ASSET_URL="${GITHUB_DOWNLOAD}/${TAG}/${ASSET_FILENAME}"
  CHECKSUM_URL=""
  if [ -n "$CHECKSUM_FILENAME" ]; then
    CHECKSUM_URL="${GITHUB_DOWNLOAD}/${TAG}/${CHECKSUM_FILENAME}"
  fi

  # --- Download and Verify ---
  TMPDIR=$(mktemp -d)
  trap 'rm -rf -- "$TMPDIR"' EXIT HUP INT TERM
  log_debug "Downloading files into ${TMPDIR}"
  log_info "Downloading ${ASSET_URL}"
  http_download "${TMPDIR}/${ASSET_FILENAME}" "${ASSET_URL}"

  # Try to find embedded checksum first
  EMBEDDED_HASH=$(find_embedded_checksum "$VERSION" "$ASSET_FILENAME")

  if [ -n "$EMBEDDED_HASH" ]; then
    log_info "Using embedded checksum for verification"
    
    # Verify using embedded hash
    got=$(hash_compute "${TMPDIR}/${ASSET_FILENAME}")
    if [ "$got" != "$EMBEDDED_HASH" ]; then
      log_crit "Checksum verification failed for ${ASSET_FILENAME}"
      log_crit "Expected: ${EMBEDDED_HASH}"
      log_crit "Got: ${got}"
      return 1
    fi
    log_info "Checksum verification successful"
  elif [ -n "$CHECKSUM_URL" ]; then
    # Fall back to downloading checksum file
    log_info "Downloading checksums from ${CHECKSUM_URL}"
    http_download "${TMPDIR}/${CHECKSUM_FILENAME}" "${CHECKSUM_URL}"
    log_info "Verifying checksum ..."
    hash_verify "${TMPDIR}/${ASSET_FILENAME}" "${TMPDIR}/${CHECKSUM_FILENAME}"
  else
    log_info "No checksum found, skipping verification."
  fi

  if [ -z "${EXT}" ] || [ "${EXT}" = ".exe" ]; then
    log_debug "Target is raw binary"
  else
    log_info "Extracting ${ASSET_FILENAME}..."
    (cd "${TMPDIR}" && untar "${ASSET_FILENAME}" "${STRIP_COMPONENTS}")
  fi
  BINARY_NAME='sigspy'
  if [ -z "${EXT}" ] || [ "${EXT}" = ".exe" ]; then
    BINARY_PATH="${TMPDIR}/${ASSET_FILENAME}"
  else
    BINARY_PATH="${TMPDIR}/sigspy"
  fi

  if [ "${UNAME_OS}" = "windows" ]; then
    case "${BINARY_NAME}" in *.exe) ;; *) BINARY_NAME="${BINARY_NAME}.exe" ;; esac
    case "${BINARY_PATH}" in *.exe) ;; *) BINARY_PATH="${BINARY_PATH}.exe" ;; esac
  fi

  if [ ! -f "${BINARY_PATH}" ]; then
    log_crit "Binary not found: ${BINARY_PATH}"
    log_crit "Listing contents of ${TMPDIR} ..."
    if command -v find >/dev/null 2>&1; then
      cd "${TMPDIR}" && find .
    else
      cd "${TMPDIR}" && ls -R .
    fi
    return 1
  fi

  # Install the binary
  INSTALL_PATH="${BINDIR}/${BINARY_NAME}"
  log_info "Installing binary to ${INSTALL_PATH}"
  test ! -d "${BINDIR}" && install -d "${BINDIR}"
  install "${BINARY_PATH}" "${INSTALL_PATH}"
  log_info "${BINARY_NAME} installation complete!"
}

# --- Configuration  ---
NAME='sigspy'
REPO='actionutils/sigspy'
EXT='.tar.gz'

# use in logging routines
log_prefix() {
  echo "${REPO}"
}

parse_args "$@"

# --- Determine target platform ---
OS="${BINSTALLER_OS:-$(uname_os)}"
UNAME_OS="${OS}"

ARCH="${BINSTALLER_ARCH:-$(uname_arch)}"
UNAME_ARCH="${ARCH}"
log_info "Detected Platform: ${OS}/${ARCH}"

# --- Validate platform ---
uname_os_check "$OS"
uname_arch_check "$ARCH"

tag_to_version

resolve_asset_filename

execute
