name: Test Build and Run

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Build binary
        run: go build -v -o sigspy main.go

      - name: Run command
        run: |
          git cat-file tag v0.0.7 | sed -n '/-BEGIN/, /-END/p' | sed 's/^ //g' | sed 's/gpgsig //g' | ./sigspy -input-format=pkcs7 | jq -S .
