name: Test Build and Run

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test-build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - name: Checkout code with tags
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: 'go.mod'

      - name: Build binary
        run: go build -v -o sigspy main.go

      - name: gitsign (-input-format=pkcs7)
        run: |
          set -euo pipefail
          git cat-file tag v1.0.0 |
            sed -n '/-BEGIN/, /-END/p' |
            sed 's/^ //g' |
            sed 's/gpgsig //g' |
            ./sigspy -input-format=pkcs7 |
            jq -S .

      - name: checksum.pem (-input-format=pem)
        run: |
          set -euo pipefail
          curl -sL https://github.com/actionutils/sigspy/releases/download/v1.0.0/checksums.txt.pem |
            base64 -d |
            ./sigspy -input-format=pem |
            jq -S .

      - name: gh attestation (-input-format=der)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          wget https://github.com/actionutils/sigspy/releases/download/v1.0.0/checksums.txt
          gh attestation verify checksums.txt --owner actionutils --format json |
            jq -r '.[0].attestation.bundle.verificationMaterial.certificate.rawBytes' |
            base64 -d |
            ./sigspy -input-format=der |
            jq -S .

      - name: gh attestation download JSONL (-input-format=pem)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          wget -O test-install.sh https://github.com/actionutils/sigspy/releases/download/v1.0.0/install.sh
          gh attestation download test-install.sh --owner actionutils
          # Find the JSONL file
          jsonl_file=$(ls *.jsonl | head -1)
          cat "$jsonl_file" |
            jq -r '.verificationMaterial.tlogEntries[0].canonicalizedBody' |
            base64 -d |
            jq -r '.spec.signatures[0].verifier' |
            base64 -d |
            ./sigspy -input-format=pem |
            jq -S .

