name: Test Build and Run

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Build binary
        run: go build -v -o sigspy main.go

      - name: gitsign (-input-format=pkcs7)
        run: |
          set -euo pipefail
          git cat-file tag v1.0.0 |
            sed -n '/-BEGIN/, /-END/p' |
            sed 's/^ //g' |
            sed 's/gpgsig //g' |
            ./sigspy -input-format=pkcs7 |
            jq -S .

      - name: checksum.pem (-input-format=pem)
        run: |
          set -euo pipefail
          curl -sL https://github.com/actionutils/sigspy/releases/download/v1.0.0/checksums.txt.pem |
            base64 -d |
            ./sigspy -input-format=pem |
            jq -S .

      - name: gh attestation (-input-format=der)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          wget https://github.com/actionutils/sigspy/releases/download/v1.0.0/checksums.txt
          gh attestation verify checksums.txt --owner actionutils --format json |
            jq -r '.[0].attestation.bundle.verificationMaterial.certificate.rawBytes' |
            base64 -d |
            ./sigspy -input-format=der |
            jq -S .

